version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gym_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gym_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/001-init_db.sql:/docker-entrypoint-initdb.d/migrations/001-init_db.sql

volumes:
  postgres_data: